---
title: "STA303 Assignment 2"
author: 
- Talia Fabregas
- Kasandra Tworzynaski
date: \today
date-format: long
number-sections: true
output: pdf_document
---

# Motorcycle deaths
```{r, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
library(Hmisc)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# retrieving the data
theUrl = "http://pbrown.ca/teaching/appliedstats/data/motorcycle.rds"
theFile = basename(theUrl)
if (!file.exists(theFile)) download.file(theUrl, theFile)
x = readRDS(theFile)

# preparing the data
x$dateInt = as.integer(x$date)
x$logMonthDays = log(Hmisc::monthDays(x$date))
x$month = factor(format(x$date, "%b"), levels = format(ISOdate(2000,
+   1:12, 1), "%b"))
res = glm(killed ~ offset(logMonthDays) + dateInt + month, data = x, family = poisson(link = "log"))
newdata = data.frame(date = seq(as.Date("1975/1/1"), as.Date("2030/1/1"), by = "month"))
newdata$dateInt = as.integer(newdata$date)
newdata$logMonthDays = log(30)
newdata$month = "Mar"
pred1 = predict(res, newdata)
newdata$month = format(newdata$date, "%b")
pred2 = predict(res, newdata)
plot(x$date, x$killed, cex = 0.2, log = "y", xlab = "", ylab = "")
matlines(newdata$date, exp(cbind(pred1, pred2)), lty = 1)
```

1. Equations for a generalized additive model

2. R code to fit the model